name: Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: { }
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Configure Git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
      - name: Generate and push changelog
        run: |
          if ! bundle exec github_changelog_generator -u "$GITHUB_REPOSITORY_OWNER" -p "$(basename $GITHUB_REPOSITORY)"; then
            echo "Failed to generate changelog"
            exit 1
          fi
          if [[ -n $(git status --porcelain CHANGELOG.md) ]]; then
            git add CHANGELOG.md
            git commit -m "[skip ci] Update changelog"
            git push
          else
            echo "No changes to changelog"
          fi