name: Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: { }

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: '${{ secrets.PAT }}'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Configure Git
        run: |
          git config user.name "svckdev"
          git config user.email "143152301+svckdev@users.noreply.github.com"
      - name: Generate and push changelog
        run: |
          if ! bundle exec github_changelog_generator -u "$GITHUB_REPOSITORY_OWNER" -p "$(basename "$GITHUB_REPOSITORY")"; then
            echo "Failed to generate changelog"
            exit 1
          fi
          if [[ -n $(git status --porcelain CHANGELOG.md) ]]; then
            git add CHANGELOG.md
            if ! git commit -m "[skip ci] Update changelog"; then
              echo "Failed to commit changes"
              exit 1
            fi
            if ! git push; then
              echo "Failed to push changes"
              exit 1
            fi
          else
            echo "No changes to changelog"
          fi
