name: Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Configure Git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
      - name: Generate and push changelog
        run: |
          bundle exec github_changelog_generator -u svck-dev -p ikibana;
          git add CHANGELOG.md;
          git commit -m "[skip ci] Update changelog";
          git push;
          
